const UPDATE_SETTINGS_START = "UPDATE_SETTINGS_START";
const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
const UPDATE_SETTINGS_ERROR = "UPDATE_SETTINGS_ERROR";

export default {
  UPDATE_SETTINGS_START,
  UPDATE_SETTINGS_SUCCESS,
  UPDATE_SETTINGS_ERROR,
};
