const REGISTER_START = "REGISTER_START";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR";

export default {
  REGISTER_START,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
};
