const FETCH_TAGS_START = "FETCH_TAGS_START";
const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
const FETCH_TAGS_ERROR = "FETCH_TAGS_ERROR";

export default {
  FETCH_TAGS_START,
  FETCH_TAGS_SUCCESS,
  FETCH_TAGS_ERROR,
};
