const SAVE_VIEWER = "SAVE_VIEWER";
const LOGOUT = "LOGOUT";

const GET_VIEWER_START = "GET_VIEWER_START";
const GET_VIEWER_SUCCESS = "GET_VIEWER_SUCCESS";
const GET_VIEWER_ERROR = "GET_VIEWER_ERROR";

export default {
  SAVE_VIEWER,
  LOGOUT,
  GET_VIEWER_START,
  GET_VIEWER_SUCCESS,
  GET_VIEWER_ERROR,
};
