const FETCH_FEED_START = "FETCH_FEED_START";
const FETCH_FEED_SUCCESS = "FETCH_FEED_SUCCESS";
const FETCH_FEED_ERROR = "FETCH_FEED_ERROR";

export default {
  FETCH_FEED_START,
  FETCH_FEED_SUCCESS,
  FETCH_FEED_ERROR,
};
