const CREATE_ARTICLE_START = "CREATE_ARTICLE_START";
const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
const CREATE_ARTICLE_ERROR = "CREATE_ARTICLE_ERROR";

export default {
  CREATE_ARTICLE_START,
  CREATE_ARTICLE_SUCCESS,
  CREATE_ARTICLE_ERROR,
};
