const FETCH_ARTICLE_START = "FETCH_ARTICLE_START";
const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
const FETCH_ARTICLE_ERROR = "FETCH_ARTICLE_ERROR";

const FETCH_ARTICLE_COMMENTS_START = "FETCH_ARTICLE_COMMENTS_START";
const FETCH_ARTICLE_COMMENTS_SUCCESS = "FETCH_ARTICLE_COMMENTS_SUCCESS";
const FETCH_ARTICLE_COMMENTS_ERROR = "FETCH_ARTICLE_COMMENTS_ERROR";

export default {
  FETCH_ARTICLE_START,
  FETCH_ARTICLE_SUCCESS,
  FETCH_ARTICLE_ERROR,
  FETCH_ARTICLE_COMMENTS_START,
  FETCH_ARTICLE_COMMENTS_SUCCESS,
  FETCH_ARTICLE_COMMENTS_ERROR,
};
