const FETCH_ARTICLE_START = "FETCH_ARTICLE_START";
const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
const FETCH_ARTICLE_ERROR = "FETCH_ARTICLE_ERROR";

const FETCH_ARTICLE_COMMENTS_START = "FETCH_ARTICLE_COMMENTS_START";
const FETCH_ARTICLE_COMMENTS_SUCCESS = "FETCH_ARTICLE_COMMENTS_SUCCESS";
const FETCH_ARTICLE_COMMENTS_ERROR = "FETCH_ARTICLE_COMMENTS_ERROR";

const POST_COMMENT_START = "POST_COMMENT_START";
const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
const POST_COMMENT_ERROR = "POST_COMMENT_ERROR";

const FAVORITE_ARTICLE_START = "FAVORITE_ARTICLE_START";
const FAVORITE_ARTICLE_SUCCESS = "FAVORITE_ARTICLE_SUCCESS";
const FAVORITE_ARTICLE_ERROR = "FAVORITE_ARTICLE_ERROR";

const UN_FAVORITE_ARTICLE_START = "UN_FAVORITE_ARTICLE_START";
const UN_FAVORITE_ARTICLE_SUCCESS = "UN_FAVORITE_ARTICLE_SUCCESS";
const UN_FAVORITE_ARTICLE_ERROR = "FAVORITE_ARTICLE_ERROR";

export default {
  FETCH_ARTICLE_START,
  FETCH_ARTICLE_SUCCESS,
  FETCH_ARTICLE_ERROR,
  FETCH_ARTICLE_COMMENTS_START,
  FETCH_ARTICLE_COMMENTS_SUCCESS,
  FETCH_ARTICLE_COMMENTS_ERROR,
  POST_COMMENT_START,
  POST_COMMENT_SUCCESS,
  POST_COMMENT_ERROR,
  FAVORITE_ARTICLE_START,
  FAVORITE_ARTICLE_SUCCESS,
  FAVORITE_ARTICLE_ERROR,
  UN_FAVORITE_ARTICLE_START,
  UN_FAVORITE_ARTICLE_SUCCESS,
  UN_FAVORITE_ARTICLE_ERROR,
};
