const FETCH_PROFILE_START = "FETCH_PROFILE_START";
const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";

const FETCH_PROFILE_ARTICLES_START = "FETCH_PROFILE_ARTICLES_START";
const FETCH_PROFILE_ARTICLES_SUCCESS = "FETCH_PROFILE_ARTICLES_SUCCESS";
const FETCH_PROFILE_ARTICLES_ERROR = "FETCH_PROFILE_ARTICLES_ERROR";

export default {
  FETCH_PROFILE_START,
  FETCH_PROFILE_SUCCESS,
  FETCH_PROFILE_ERROR,
  FETCH_PROFILE_ARTICLES_START,
  FETCH_PROFILE_ARTICLES_SUCCESS,
  FETCH_PROFILE_ARTICLES_ERROR,
};
